SELECT            
 rownum,     
 S.MODULE,
 S.SQL_TEXT, 
 S.SQL_PROFILE,
 S.EXECUTIONS,
 S.LAST_LOAD_TIME,
 S.PARSING_USER_ID,
 S.SERVICE  ,  
 S.USERS_OPENING,
  TO_CHAR(S.LAST_ACTIVE_TIME, 'YYYY-MM-DD HH24:MI:SS')
 FROM SYS.V_$SQL S, SYS.ALL_USERS U WHERE S.PARSING_USER_ID=U.USER_ID 
 AND UPPER(U.USERNAME) IN ('OUCHNSYS')   
ORDER BY S.LAST_ACTIVE_TIME desc;
