--
-- TCPCOURSE  (Type) 
--
CREATE OR REPLACE TYPE OUCHNSYS.TCPCOURSE AS OBJECT
(
  BATCHCODE VARCHAR2(50),
  TCPCODE VARCHAR2(50),
  MODULECODE VARCHAR2(50),
  COURSEID VARCHAR2(50),
  CREDIT NUMBER(7,2),
  COURSENATURE VARCHAR2(2),
  SEMESTER NUMBER(2),
  EXAMUNITTYPE VARCHAR2(10),
  IsDegreeCourse number,
  IsExecutiveCourse number
  
)
/

