--
-- TYP_EXECMODULECOURSE  (Type) 
--
CREATE OR REPLACE TYPE OUCHNSYS."TYP_EXECMODULECOURSE"                                                                                   AS OBJECT 
(
  COURSEID VARCHAR2(10),
  MODULECODE VARCHAR2(10),
  CREDIT NUMBER(7,2),
  COURSESTATE NUMBER(1),
  OPENEDSEMESTER NUMBER(2),
  COURSENATURE NUMBER(1),
  EXAMUNITTYPE NUMBER(1)
  
)
/

